apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: tetris
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    azure.workload.identity/use: "true"
  name: test
  namespace: tetris
spec:
  containers:
    - command:
        - /manager
      image: docker.io/test:v1
      name: test
  serviceAccountName: controller