apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: tetris
  annotations:
    azure.workload.identity/client-id: "d56285d4-63f7-4bef-a832-cf062a85db23"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    azure.workload.identity/use: "true"
  name: test
  namespace: tetris
spec:
  containers:
    - command:
        - /manager
      image: docker.io/jrbancel/test:v1
      name: test
  serviceAccountName: controller
