apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: github.com/JRBANCEL/Experimental/TracePropagation/cmd/backend
